config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    omniauth_callbacks: 'users/omniauth_callbacks',
    registrations: 'users/registrations'
  }
  root to: 'posts#index'
  resources :posts do
    resources :comments, only: :create
    resource :likes, only: [:create, :destroy]
    collection do
      get 'search'
    end
    collection do
      get 'search_tag'
    end
  end
  resources :users, only: :show do
    resource :relationships, only: [:create, :destroy]
    resources :transactions, only: [:index, :create]
  end
end

app/models/post.rb
class Post < ApplicationRecord
  extend ActiveHash::Associations::ActiveRecordExtensions
  has_many :comments
  has_many :likes
  has_many :post_tag_relations
  has_many :tags, through: :post_tag_relations, dependent: :destroy
  belongs_to :industry
  belongs_to :user
  has_one_attached :video

  def liked_by?(user)
    likes.where(user_id: user.id).exists?
  end

  def self.ransackable_attributes(auth_object = nil)
    ["title", "description", "industry_id"]
  end

  def self.ransackable_associations(auth_object = nil)
    ["user"]
  end
end

app/models/post_form.rb
class PostForm
  include ActiveModel::Model

  attr_accessor(:title, :description, :video, :industry_id, :user_id, :id, :created_at, :updated_at, :tag_name) 
  with_options presence: true do
    validates :industry_id, numericality: { other_than: 1, message: "can't be blank" }
    validates :description
    validates :title, length: { maximum: 50, message: "is too long (maximum is 50 characters)"}
    validates :video
  end

  def save
  post = Post.create(title: title, video: video, description: description, industry_id: industry_id, user_id: user_id)

  if tag_name.present?
    tag = Tag.where(tag_name: tag_name).first_or_initialize
    tag.save
    PostTagRelation.create(post_id: post.id, tag_id: tag.id)
  end
end

  def update(params, post)
    post.post_tag_relations.destroy_all

    tag_name = params.delete(:tag_name)

    tag = Tag.where(tag_name: tag_name).first_or_initialize if tag_name.present?

    tag.save if tag_name.present?
    post.update(params)
    PostTagRelation.create(post_id: post.id, tag_id: tag.id) if tag_name.present?
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :user_match, only: [:edit, :update, :destroy]
  before_action :post_find, only: [:show, :update, :destroy]
  def index
    @posts = Post.order("created_at DESC")
  end
# new 
# create 
  def new
    @post_form = PostForm.new
  end

  def create
    @post_form = PostForm.new(post_form_params)
    if @post_form.valid?
       @post_form.save
       redirect_to root_path
    else
      render :new, status: :unprocessable_entity
    end
  end

  def show
    @comment = Comment.new
    @comments = @post.comments.includes(:user)
  end

  def edit
    post_attributes = @post.attributes
    @post_form = PostForm.new(post_attributes)
    @post_form.tag_name = @post.tags.first&.tag_name
  end

  def update
    @post_form = PostForm.new(post_form_params)
    @post_form.video ||= @post.video.blob
    if @post_form.valid?
      @post_form.update(post_form_params, @post)
      redirect_to post_path(@post.id)
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @post.destroy
    redirect_to root_path
  end

  def search
    @q = Post.ransack(params[:q])
    @posts = @q.result(distinct: true)
  end

  def search_tag
    return nil if params[:keyword] == ""
    tag = Tag.where(['tag_name LIKE ?', "%#{params[:keyword]}%"] )
    render json:{ keyword: tag }
  end


  private
  def post_form_params
    params.require(:post_form).permit(:title, :description, :video, :industry_id, :tag_name).merge(user_id: current_user.id)
  end

  def user_match
    @post = Post.find(params[:id])
    if @post.user != current_user
      redirect_to root_path
    end
  end

  def post_find
    @post = Post.find(params[:id])
  end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_header.html.erb
<header>
  <%= link_to "キャリアリハーサル", root_path %>
  <% if user_signed_in? %>
    <p><%= link_to "新規投稿", new_post_path %></p>
    <p><%= link_to "ログアウト", destroy_user_session_path, data: { turbo_method: :delete } %></p>
  <% else %>
    <p><%= link_to "新規登録", new_user_registration_path %></p>
    <p><%= link_to "ログイン", new_user_session_path %></p>
  <% end %>
  <%= link_to '商品検索', search_posts_path%>
</header>

app/views/posts/_post.html.erb
<div class="form-container">
  <%= form_with(model: @post_form, url: url, method: method, local: true, id: "new_post") do |f|%>
    <div class="error-messages">
      <%= render "shared/error_messages", model: f.object %>
    </div>

    <div class="form-field">
      <%= f.label :video %>
      <%= f.file_field :video %>
    </div>

    <div class="form-field">
      <%= f.label :title, "タイトル" %>
      <%= f.text_field :title, placeholder: "タイトルを入力" %>
    </div>
    <div class="tag-field">
      <%= f.text_field :tag_name, placeholder: 'add tags' %>
      <div id="search-result"></div>
    </div>
    <div class="form-field">
      <%= f.label :description, "説明" %>
      <%= f.text_area :description, placeholder: "説明を入力" %>
    </div>

    <div class="form-field">
      <%= f.label :industry_id, "業種" %>
      <%= f.collection_select(:industry_id, Industry.all, :id, :name, {}, {class: 'select-field'}) %>
    </div>

    <div class="actions">
      <%= f.submit "送信", class: "submit-btn" %>
    </div>
  <% end %>
</div>

<%# direct_upload: true これはf.file_fieldに追記する。ストレージサービスを使うときにこれで先にストレージサービスにアップロードされる %>

app/views/posts/edit.html.erb
<%= render partial: "header" %>
<%= render partial: 'post', locals: {url: post_path(@post.id), method: :patch} %>

app/views/posts/index.html.erb
<%= stylesheet_link_tag 'application', media: 'all', 'data-turbo-track': 'reload' %>
<%= render partial: "header" %>
<div class="post-container">
  <% @posts.each do |post| %>
    <div class="post">
      <% if post.video.attached? %>
        <p><%= video_tag(rails_blob_path(post.video), controls: true) %></p>
      <% end %>
      <h2 class="post-title"><%= post.title %></h2>
      <p>投稿内容 : <%= post.description %></p>
      <p class="industry">業種 : <%= post.industry.name %></p>
      <p><%= link_to "詳細", post_path(post.id), data: { turbo: false } %></p>
      <div id="like-btn<%= post.id %>" class="like-btn">
        <%= turbo_frame_tag dom_id(post, :like) do %>
          <% if user_signed_in? && post.liked_by?(current_user) %>
            <%= link_to "いいね済", post_likes_path(post.id), data: { turbo_method: :delete } %>
          <% else %>
            <%= link_to "いいね", post_likes_path(post.id), data: { turbo_method: :post } %>
          <% end %>
        <% end %>
      </div>
    </div>
  <% end %>
</div>

app/views/posts/new.html.erb
<%= render partial: "header" %>
<%= render partial: 'post', locals: {url: posts_path, method: :post} %>

app/views/posts/search.html.erb
<%= stylesheet_link_tag 'application', media: 'all', 'data-turbo-track': 'reload' %>
<header>
  <%= link_to "キャリアリハーサル", root_path %>
  <% if user_signed_in? %>
    <p><%= link_to "新規投稿", new_post_path %></p>
    <p><%= link_to "ログアウト", destroy_user_session_path, data: { turbo_method: :delete } %></p>
  <% else %>
    <p><%= link_to "新規登録", new_user_registration_path %></p>
    <p><%= link_to "ログイン", new_user_session_path %></p>
  <% end %>
  <%= search_form_for @q, url: search_posts_path, html: {id: "detailed-search-form"} do |f| %>
    <div class="search-field">
      <%= f.label :user_username_cont, '出品者名' %>
      <br>
      <%= f.text_field :user_username_cont, placeholder: '出品者名' %>
    </div>
    <div class="search-field">
      <%= f.label :title, 'タイトル' %>
      <br>
      <%= f.text_field :title, placeholder: 'タイトル', value: params[:q]&.dig(:title) %>
    </div>
    <div class="search-field">
      <%= f.label :description_cont, '内容' %>
      <br>
      <%= f.text_field :description_cont, placeholder: '内容' %>
    </div>
    <div class="search-field">
      <%= f.label :industry_id_eq, '業種' %>
      <br>
      <%= f.collection_check_boxes(:industry_id_in, Industry.all, :id, :name, {}) %>
    </div>
    <%= f.submit '検索' %>
  <% end %>
</header>

<div class="post-container">
  <% @posts.each do |post| %>
    <div class="post">
      <% if post.video.attached? %>
        <p><%= video_tag(rails_blob_path(post.video), controls: true) %></p>
      <% end %>
      <h2 class="post-title"><%= post.title %></h2>
      <p><%= post.description %></p>
      <p class="industry"><%= post.industry.name %></p>
      <p><%= link_to "詳細", post_path(post.id), data: { turbo: false } %></p>
      <div id="like-btn<%= post.id %>" class="like-btn">
        <%= turbo_frame_tag dom_id(post, :like) do %>
          <% if user_signed_in? && post.liked_by?(current_user) %>
            <%= link_to "いいね済", post_likes_path(post.id), data: { turbo_method: :delete } %>
          <% else %>
            <%= link_to "いいね", post_likes_path(post.id), data: { turbo_method: :post } %>
          <% end %>
        <% end %>
      </div>
    </div>
  <% end %>
</div>

app/views/posts/show.html.erb
<%= render partial: "header" %>
<div class="form-container">
  <% if @post.video.attached? %>
    <div class="video-container">
      <%= video_tag(rails_blob_path(@post.video), controls: true, class: "video-responsive") %>
    </div>
  <% end %>
  
  <h2 class="post-title"><%= @post.title %></h2>
  <p>投稿内容 : <%= @post.description %></p>
  <p class="industry">業種 : <%= @post.industry.name %></p>

  <div class="post-actions">
    <%= link_to "投稿の編集", edit_post_path(@post.id), class: "edit-link" %>
    <%= link_to "投稿の削除", post_path(@post.id), data: { turbo_method: :delete }, class: "delete-link" %>
  </div>

  <div id="like-btn<%= @post.id %>" class="like-btn">
    <%= turbo_frame_tag dom_id(@post, :like) do %>
      <% if user_signed_in? && @post.liked_by?(current_user)%>
        <%= link_to "いいね済", post_likes_path(@post.id), data: { turbo_method: :delete }, class: "like-link" %>
      <% else %>
        <%= link_to "いいね", post_likes_path(@post.id), data: { turbo_method: :post }, class: "like-link" %>
      <% end %>
    <% end %>
  </div>

  <tr>
    <th>タグ:</th>
    <td><%= @post.tags.first&.tag_name %></td>
  </tr>
  
  <p class="username"><%= link_to @post.user.username, user_path(@post.user), class: "user-link" %></p>

  <% if user_signed_in? %>
    <div class="comment-form">
      <%= form_with(model: [@post, @comment], local: true) do |f| %>
        <div class="form-field">
          <%= f.text_area :content, placeholder: "コメントする", rows: "2" %>
        </div>
        <div class="actions">
          <%= f.submit "送信", class: "submit-btn" %>
        </div>
      <% end %>
    </div>
  <% end %>

  <div class="comments">
    <% @comments.each do |comment| %>
      <div class="comment">
        <p class="comment-username"><%= comment.user.username %></p>
        <p class="comment-content"><%= comment.content %></p>
      </div>
    <% end %>
  </div>
</div>