config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    omniauth_callbacks: 'users/omniauth_callbacks',
    registrations: 'users/registrations'
  }
  root to: 'posts#index'
  resources :posts do
    resources :comments, only: :create
    resource :likes, only: [:create, :destroy]
    collection do
      get 'search'
    end
    collection do
      get 'search_tag'
    end
  end
  resources :users, only: :show do
    resource :relationships, only: [:create, :destroy]
    resources :transactions, only: [:index, :create]
  end
end

app/controllers/transactions_controller.rb
class TransactionsController < ApplicationController
  def index
    @transaction = Transaction.new
    @user = User.find(params[:user_id])
  end

  def create
    @user = User.find(params[:user_id])
    @transaction = Transaction.new(transaction_params)
    if @transaction.valid?
      api_pay
      @transaction.save
      redirect_to root_path
    else
      render :index, status: :unprocessable_entity
    end
  end

  private
  def transaction_params
    params.require(:transaction).permit(:price, :text).merge(user_id: params[:user_id], token: params[:token])
  end
  

  def api_pay
    Payjp.api_key = "sk_test_35285d916314b9eb100df281"
      Payjp::Charge.create(
        amount: transaction_params[:price], #送金の値段
        card: transaction_params[:token], #カードトークン
        currency: "jpy" #通貨の種類
      )
  end
end

app/helpers/transactions_helper.rb
module TransactionsHelper
end

app/views/transactions/index.html.erb
<%= render partial: "posts/header" %>
<%= form_with model: @transaction, url: user_transactions_path(@user), method: :post, id: "charge-form", class: 'transaction-form-wrap', local: true, data: { turbo: "false"} do |f| %>
  <%= render 'shared/error_messages', model: f.object %>
  <%# カード情報の入力 %>
  <div class='credit-card-form'>
    <h1 class='info-input-haedline'>
      クレジットカード情報入力
    </h1>
    <div class="form-group">
      <div class='form-text-wrap'>
        <label class="form-text">カード情報</label>
        <span class="indispensable">必須</span>
      </div>
      <div id="number-form" class="input-default"></div>
      <div class='available-card'>
        <%= image_tag 'card-visa.gif', class: 'card-logo'%>
        <%= image_tag 'card-mastercard.gif', class: 'card-logo'%>
        <%= image_tag 'card-jcb.gif', class: 'card-logo'%>
        <%= image_tag 'card-amex.gif', class: 'card-logo'%>
      </div>
    </div>
    <div class="form-group">
      <div class='form-text-wrap'>
        <label class="form-text">有効期限</label>
        <span class="indispensable">必須</span>
      </div>
      <div class='input-expiration-date-wrap'>
        <div id="expiry-form" class="input-default"></div>
      </div>
    </div>
    <div class="form-group">
      <div class='form-text-wrap'>
        <label class="form-text">セキュリティコード</label>
        <span class="indispensable">必須</span>
      </div>
      <div id="cvc-form" class="input-default"></div>
    </div>
  </div>
  <%# /カード情報の入力 %>

  <%# /送金金額 %>
  <div class="form-group">
    <div class="price-form">
      <%= f.text_field :price, class: "price-input", id: "item-price", placeholder: "いくら送る？" %>
    </div>
    <div class="text-form">
      <%= f.text_area :text, class: "text-input", placeholder: "感謝の言葉を送ろう！" %>
    </div>
    <div class='buy-btn'>
      <%= f.submit "購入" ,class:"buy-red-btn", id:"button" %>
    </div>
  </div>
<% end %>